#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrotop.ReporteControlPlanta
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="agrofichas_produccion")]
	public partial class AgroFichasDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEmpresa(Empresa instance);
    partial void UpdateEmpresa(Empresa instance);
    partial void DeleteEmpresa(Empresa instance);
    #endregion
		
		public AgroFichasDBDataContext() : 
				base(global::Agrotop.ReporteControlPlanta.Properties.Settings.Default.agrofichas_produccionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichasDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichasDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichasDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichasDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Empresa> Empresa
		{
			get
			{
				return this.GetTable<Empresa>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.rpt_CTR_EncabezadoControlSemanalPorEmpresa")]
		public ISingleResult<rpt_CTR_EncabezadoControlSemanalPorEmpresaResult> rpt_CTR_EncabezadoControlSemanalPorEmpresa()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<rpt_CTR_EncabezadoControlSemanalPorEmpresaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.rpt_CTR_DetalleControlSemanalPorEmpresa")]
		public ISingleResult<rpt_CTR_DetalleControlSemanalPorEmpresaResult> rpt_CTR_DetalleControlSemanalPorEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="Int")] System.Nullable<int> idEmpresa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa);
			return ((ISingleResult<rpt_CTR_DetalleControlSemanalPorEmpresaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.rpt_CTR_ResumenControlSemanalPorEmpresa")]
		public ISingleResult<rpt_CTR_ResumenControlSemanalPorEmpresaResult> rpt_CTR_ResumenControlSemanalPorEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="Int")] System.Nullable<int> idEmpresa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa);
			return ((ISingleResult<rpt_CTR_ResumenControlSemanalPorEmpresaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empresa")]
	public partial class Empresa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEmpresa;
		
		private string _Nombre;
		
		private string _Sigla;
		
		private string _UserIns;
		
		private System.DateTime _FechaHoraIns;
		
		private string _IpIns;
		
		private string _UserUpd;
		
		private System.Nullable<System.DateTime> _FechaHoraUpd;
		
		private string _IpUpd;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEmpresaChanging(int value);
    partial void OnIdEmpresaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnSiglaChanging(string value);
    partial void OnSiglaChanged();
    partial void OnUserInsChanging(string value);
    partial void OnUserInsChanged();
    partial void OnFechaHoraInsChanging(System.DateTime value);
    partial void OnFechaHoraInsChanged();
    partial void OnIpInsChanging(string value);
    partial void OnIpInsChanged();
    partial void OnUserUpdChanging(string value);
    partial void OnUserUpdChanged();
    partial void OnFechaHoraUpdChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraUpdChanged();
    partial void OnIpUpdChanging(string value);
    partial void OnIpUpdChanged();
    #endregion
		
		public Empresa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this.OnIdEmpresaChanging(value);
					this.SendPropertyChanging();
					this._IdEmpresa = value;
					this.SendPropertyChanged("IdEmpresa");
					this.OnIdEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sigla", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Sigla
		{
			get
			{
				return this._Sigla;
			}
			set
			{
				if ((this._Sigla != value))
				{
					this.OnSiglaChanging(value);
					this.SendPropertyChanging();
					this._Sigla = value;
					this.SendPropertyChanged("Sigla");
					this.OnSiglaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIns", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserIns
		{
			get
			{
				return this._UserIns;
			}
			set
			{
				if ((this._UserIns != value))
				{
					this.OnUserInsChanging(value);
					this.SendPropertyChanging();
					this._UserIns = value;
					this.SendPropertyChanged("UserIns");
					this.OnUserInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraIns", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHoraIns
		{
			get
			{
				return this._FechaHoraIns;
			}
			set
			{
				if ((this._FechaHoraIns != value))
				{
					this.OnFechaHoraInsChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraIns = value;
					this.SendPropertyChanged("FechaHoraIns");
					this.OnFechaHoraInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpIns", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IpIns
		{
			get
			{
				return this._IpIns;
			}
			set
			{
				if ((this._IpIns != value))
				{
					this.OnIpInsChanging(value);
					this.SendPropertyChanging();
					this._IpIns = value;
					this.SendPropertyChanged("IpIns");
					this.OnIpInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserUpd", DbType="VarChar(50)")]
		public string UserUpd
		{
			get
			{
				return this._UserUpd;
			}
			set
			{
				if ((this._UserUpd != value))
				{
					this.OnUserUpdChanging(value);
					this.SendPropertyChanging();
					this._UserUpd = value;
					this.SendPropertyChanged("UserUpd");
					this.OnUserUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraUpd", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaHoraUpd
		{
			get
			{
				return this._FechaHoraUpd;
			}
			set
			{
				if ((this._FechaHoraUpd != value))
				{
					this.OnFechaHoraUpdChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraUpd = value;
					this.SendPropertyChanged("FechaHoraUpd");
					this.OnFechaHoraUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpUpd", DbType="VarChar(50)")]
		public string IpUpd
		{
			get
			{
				return this._IpUpd;
			}
			set
			{
				if ((this._IpUpd != value))
				{
					this.OnIpUpdChanging(value);
					this.SendPropertyChanging();
					this._IpUpd = value;
					this.SendPropertyChanged("IpUpd");
					this.OnIpUpdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class rpt_CTR_EncabezadoControlSemanalPorEmpresaResult
	{
		
		private System.Nullable<int> _NumeroSemana;
		
		private System.Nullable<System.DateTime> _PrimerDiaSemanaPasada;
		
		private System.Nullable<System.DateTime> _UltimoDiaSemanaPasada;
		
		public rpt_CTR_EncabezadoControlSemanalPorEmpresaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroSemana", DbType="Int")]
		public System.Nullable<int> NumeroSemana
		{
			get
			{
				return this._NumeroSemana;
			}
			set
			{
				if ((this._NumeroSemana != value))
				{
					this._NumeroSemana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerDiaSemanaPasada", DbType="Date")]
		public System.Nullable<System.DateTime> PrimerDiaSemanaPasada
		{
			get
			{
				return this._PrimerDiaSemanaPasada;
			}
			set
			{
				if ((this._PrimerDiaSemanaPasada != value))
				{
					this._PrimerDiaSemanaPasada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoDiaSemanaPasada", DbType="Date")]
		public System.Nullable<System.DateTime> UltimoDiaSemanaPasada
		{
			get
			{
				return this._UltimoDiaSemanaPasada;
			}
			set
			{
				if ((this._UltimoDiaSemanaPasada != value))
				{
					this._UltimoDiaSemanaPasada = value;
				}
			}
		}
	}
	
	public partial class rpt_CTR_DetalleControlSemanalPorEmpresaResult
	{
		
		private System.Nullable<int> _IdEmpresa;
		
		private int _IdProducto;
		
		private string _Producto;
		
		private System.Nullable<int> _IdEnvase;
		
		private string _Envase;
		
		private System.DateTime _FechaLlegada;
		
		private System.Nullable<System.DateTime> _FechaPesajeInicial;
		
		private System.Nullable<System.DateTime> _FechaPesajeFinal;
		
		private System.Nullable<System.DateTime> _FechaSalida;
		
		private System.Nullable<int> _IngresoPlanta;
		
		private System.Nullable<int> _Romana;
		
		private System.Nullable<int> _SalidaPlanta;
		
		private System.Nullable<int> _EstadiaEnPlanta;
		
		public rpt_CTR_DetalleControlSemanalPorEmpresaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="Int")]
		public System.Nullable<int> IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this._IdEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this._Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEnvase", DbType="Int")]
		public System.Nullable<int> IdEnvase
		{
			get
			{
				return this._IdEnvase;
			}
			set
			{
				if ((this._IdEnvase != value))
				{
					this._IdEnvase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Envase", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Envase
		{
			get
			{
				return this._Envase;
			}
			set
			{
				if ((this._Envase != value))
				{
					this._Envase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaLlegada", DbType="DateTime NOT NULL")]
		public System.DateTime FechaLlegada
		{
			get
			{
				return this._FechaLlegada;
			}
			set
			{
				if ((this._FechaLlegada != value))
				{
					this._FechaLlegada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPesajeInicial", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaPesajeInicial
		{
			get
			{
				return this._FechaPesajeInicial;
			}
			set
			{
				if ((this._FechaPesajeInicial != value))
				{
					this._FechaPesajeInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPesajeFinal", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaPesajeFinal
		{
			get
			{
				return this._FechaPesajeFinal;
			}
			set
			{
				if ((this._FechaPesajeFinal != value))
				{
					this._FechaPesajeFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSalida", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaSalida
		{
			get
			{
				return this._FechaSalida;
			}
			set
			{
				if ((this._FechaSalida != value))
				{
					this._FechaSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngresoPlanta", DbType="Int")]
		public System.Nullable<int> IngresoPlanta
		{
			get
			{
				return this._IngresoPlanta;
			}
			set
			{
				if ((this._IngresoPlanta != value))
				{
					this._IngresoPlanta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Romana", DbType="Int")]
		public System.Nullable<int> Romana
		{
			get
			{
				return this._Romana;
			}
			set
			{
				if ((this._Romana != value))
				{
					this._Romana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalidaPlanta", DbType="Int")]
		public System.Nullable<int> SalidaPlanta
		{
			get
			{
				return this._SalidaPlanta;
			}
			set
			{
				if ((this._SalidaPlanta != value))
				{
					this._SalidaPlanta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadiaEnPlanta", DbType="Int")]
		public System.Nullable<int> EstadiaEnPlanta
		{
			get
			{
				return this._EstadiaEnPlanta;
			}
			set
			{
				if ((this._EstadiaEnPlanta != value))
				{
					this._EstadiaEnPlanta = value;
				}
			}
		}
	}
	
	public partial class rpt_CTR_ResumenControlSemanalPorEmpresaResult
	{
		
		private int _IdProducto;
		
		private string _Producto;
		
		private System.Nullable<int> _IdEnvase;
		
		private string _Envase;
		
		private System.Nullable<int> _NControles;
		
		private System.Nullable<int> _IngresoPlanta;
		
		private System.Nullable<int> _Romana;
		
		private System.Nullable<int> _SalidaPlanta;
		
		private System.Nullable<int> _Promedio;
		
		public rpt_CTR_ResumenControlSemanalPorEmpresaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this._Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEnvase", DbType="Int")]
		public System.Nullable<int> IdEnvase
		{
			get
			{
				return this._IdEnvase;
			}
			set
			{
				if ((this._IdEnvase != value))
				{
					this._IdEnvase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Envase", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Envase
		{
			get
			{
				return this._Envase;
			}
			set
			{
				if ((this._Envase != value))
				{
					this._Envase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NControles", DbType="Int")]
		public System.Nullable<int> NControles
		{
			get
			{
				return this._NControles;
			}
			set
			{
				if ((this._NControles != value))
				{
					this._NControles = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngresoPlanta", DbType="Int")]
		public System.Nullable<int> IngresoPlanta
		{
			get
			{
				return this._IngresoPlanta;
			}
			set
			{
				if ((this._IngresoPlanta != value))
				{
					this._IngresoPlanta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Romana", DbType="Int")]
		public System.Nullable<int> Romana
		{
			get
			{
				return this._Romana;
			}
			set
			{
				if ((this._Romana != value))
				{
					this._Romana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalidaPlanta", DbType="Int")]
		public System.Nullable<int> SalidaPlanta
		{
			get
			{
				return this._SalidaPlanta;
			}
			set
			{
				if ((this._SalidaPlanta != value))
				{
					this._SalidaPlanta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promedio", DbType="Int")]
		public System.Nullable<int> Promedio
		{
			get
			{
				return this._Promedio;
			}
			set
			{
				if ((this._Promedio != value))
				{
					this._Promedio = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
