#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroFichasLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="agrofichas")]
	public partial class AgroFichaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertSYS_User(SYS_User instance);
    partial void UpdateSYS_User(SYS_User instance);
    partial void DeleteSYS_User(SYS_User instance);
    #endregion
		
		public AgroFichaDBDataContext() : 
				base(global::AgroFichasLib.Properties.Settings.Default.agrofichasConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SYS_User> SYS_User
		{
			get
			{
				return this.GetTable<SYS_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYS_User")]
	public partial class SYS_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _UserName;
		
		private string _FullName;
		
		private string _Password;
		
		private bool _Disabled;
		
		private System.Nullable<System.DateTime> _LastLogin;
		
		private string _Email;
		
		private string _UserIns;
		
		private System.DateTime _FechaHoraIns;
		
		private string _IpIns;
		
		private string _UserUpd;
		
		private System.Nullable<System.DateTime> _FechaHoraUpd;
		
		private string _IpUpd;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnDisabledChanging(bool value);
    partial void OnDisabledChanged();
    partial void OnLastLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUserInsChanging(string value);
    partial void OnUserInsChanged();
    partial void OnFechaHoraInsChanging(System.DateTime value);
    partial void OnFechaHoraInsChanged();
    partial void OnIpInsChanging(string value);
    partial void OnIpInsChanged();
    partial void OnUserUpdChanging(string value);
    partial void OnUserUpdChanged();
    partial void OnFechaHoraUpdChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraUpdChanged();
    partial void OnIpUpdChanging(string value);
    partial void OnIpUpdChanged();
    #endregion
		
		public SYS_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Bit NOT NULL")]
		public bool Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogin", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> LastLogin
		{
			get
			{
				return this._LastLogin;
			}
			set
			{
				if ((this._LastLogin != value))
				{
					this.OnLastLoginChanging(value);
					this.SendPropertyChanging();
					this._LastLogin = value;
					this.SendPropertyChanged("LastLogin");
					this.OnLastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIns", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserIns
		{
			get
			{
				return this._UserIns;
			}
			set
			{
				if ((this._UserIns != value))
				{
					this.OnUserInsChanging(value);
					this.SendPropertyChanging();
					this._UserIns = value;
					this.SendPropertyChanged("UserIns");
					this.OnUserInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraIns", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHoraIns
		{
			get
			{
				return this._FechaHoraIns;
			}
			set
			{
				if ((this._FechaHoraIns != value))
				{
					this.OnFechaHoraInsChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraIns = value;
					this.SendPropertyChanged("FechaHoraIns");
					this.OnFechaHoraInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpIns", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IpIns
		{
			get
			{
				return this._IpIns;
			}
			set
			{
				if ((this._IpIns != value))
				{
					this.OnIpInsChanging(value);
					this.SendPropertyChanging();
					this._IpIns = value;
					this.SendPropertyChanged("IpIns");
					this.OnIpInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserUpd", DbType="VarChar(50)")]
		public string UserUpd
		{
			get
			{
				return this._UserUpd;
			}
			set
			{
				if ((this._UserUpd != value))
				{
					this.OnUserUpdChanging(value);
					this.SendPropertyChanging();
					this._UserUpd = value;
					this.SendPropertyChanged("UserUpd");
					this.OnUserUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraUpd", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaHoraUpd
		{
			get
			{
				return this._FechaHoraUpd;
			}
			set
			{
				if ((this._FechaHoraUpd != value))
				{
					this.OnFechaHoraUpdChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraUpd = value;
					this.SendPropertyChanged("FechaHoraUpd");
					this.OnFechaHoraUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpUpd", DbType="VarChar(50)")]
		public string IpUpd
		{
			get
			{
				return this._IpUpd;
			}
			set
			{
				if ((this._IpUpd != value))
				{
					this.OnIpUpdChanging(value);
					this.SendPropertyChanging();
					this._IpUpd = value;
					this.SendPropertyChanged("IpUpd");
					this.OnIpUpdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
