#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarteraAsesorAgricola
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="agrofichas")]
	public partial class AgroFichasDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAgricultor(Agricultor instance);
    partial void UpdateAgricultor(Agricultor instance);
    partial void DeleteAgricultor(Agricultor instance);
    partial void InsertSYS_User(SYS_User instance);
    partial void UpdateSYS_User(SYS_User instance);
    partial void DeleteSYS_User(SYS_User instance);
    partial void InsertUsuarioAgricultor(UsuarioAgricultor instance);
    partial void UpdateUsuarioAgricultor(UsuarioAgricultor instance);
    partial void DeleteUsuarioAgricultor(UsuarioAgricultor instance);
    #endregion
		
		public AgroFichasDBDataContext() : 
				base(global::CarteraAsesorAgricola.Properties.Settings.Default.agrofichasConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichasDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichasDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichasDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgroFichasDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Agricultor> Agricultor
		{
			get
			{
				return this.GetTable<Agricultor>();
			}
		}
		
		public System.Data.Linq.Table<SYS_User> SYS_User
		{
			get
			{
				return this.GetTable<SYS_User>();
			}
		}
		
		public System.Data.Linq.Table<UsuarioAgricultor> UsuarioAgricultor
		{
			get
			{
				return this.GetTable<UsuarioAgricultor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Agricultor")]
	public partial class Agricultor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAgricultor;
		
		private string _Rut;
		
		private string _Nombre;
		
		private string _Email;
		
		private bool _Habilitado;
		
		private int _IdProveedor;
		
		private string _MobileTag;
		
		private string _UserIns;
		
		private System.DateTime _FechaHoraIns;
		
		private string _IpIns;
		
		private string _UserUpd;
		
		private System.Nullable<System.DateTime> _FechaHoraUpd;
		
		private string _IpUpd;
		
		private string _Fono1;
		
		private string _Fono2;
		
		private int _Origen;
		
		private string _IDOleotop;
		
		private string _IDAvenatop;
		
		private string _IDGranotop;
		
		private System.Nullable<System.DateTime> _LastSAPSync;
		
		private string _Password;
		
		private System.Nullable<System.DateTime> _LastLogin;
		
		private System.Nullable<bool> _LegacyAccessOleotop;
		
		private System.Nullable<bool> _LegacyAccessAvenatop;
		
		private System.Nullable<bool> _LegacyAccessGranotop;
		
		private System.Nullable<bool> _MustChangePassword;
		
		private string _IDSaprosem;
		
		private System.Nullable<int> _IdForceManager;
		
		private EntitySet<UsuarioAgricultor> _UsuarioAgricultor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAgricultorChanging(int value);
    partial void OnIdAgricultorChanged();
    partial void OnRutChanging(string value);
    partial void OnRutChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnHabilitadoChanging(bool value);
    partial void OnHabilitadoChanged();
    partial void OnIdProveedorChanging(int value);
    partial void OnIdProveedorChanged();
    partial void OnMobileTagChanging(string value);
    partial void OnMobileTagChanged();
    partial void OnUserInsChanging(string value);
    partial void OnUserInsChanged();
    partial void OnFechaHoraInsChanging(System.DateTime value);
    partial void OnFechaHoraInsChanged();
    partial void OnIpInsChanging(string value);
    partial void OnIpInsChanged();
    partial void OnUserUpdChanging(string value);
    partial void OnUserUpdChanged();
    partial void OnFechaHoraUpdChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraUpdChanged();
    partial void OnIpUpdChanging(string value);
    partial void OnIpUpdChanged();
    partial void OnFono1Changing(string value);
    partial void OnFono1Changed();
    partial void OnFono2Changing(string value);
    partial void OnFono2Changed();
    partial void OnOrigenChanging(int value);
    partial void OnOrigenChanged();
    partial void OnIDOleotopChanging(string value);
    partial void OnIDOleotopChanged();
    partial void OnIDAvenatopChanging(string value);
    partial void OnIDAvenatopChanged();
    partial void OnIDGranotopChanging(string value);
    partial void OnIDGranotopChanged();
    partial void OnLastSAPSyncChanging(System.Nullable<System.DateTime> value);
    partial void OnLastSAPSyncChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnLastLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginChanged();
    partial void OnLegacyAccessOleotopChanging(System.Nullable<bool> value);
    partial void OnLegacyAccessOleotopChanged();
    partial void OnLegacyAccessAvenatopChanging(System.Nullable<bool> value);
    partial void OnLegacyAccessAvenatopChanged();
    partial void OnLegacyAccessGranotopChanging(System.Nullable<bool> value);
    partial void OnLegacyAccessGranotopChanged();
    partial void OnMustChangePasswordChanging(System.Nullable<bool> value);
    partial void OnMustChangePasswordChanged();
    partial void OnIDSaprosemChanging(string value);
    partial void OnIDSaprosemChanged();
    partial void OnIdForceManagerChanging(System.Nullable<int> value);
    partial void OnIdForceManagerChanged();
    #endregion
		
		public Agricultor()
		{
			this._UsuarioAgricultor = new EntitySet<UsuarioAgricultor>(new Action<UsuarioAgricultor>(this.attach_UsuarioAgricultor), new Action<UsuarioAgricultor>(this.detach_UsuarioAgricultor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAgricultor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAgricultor
		{
			get
			{
				return this._IdAgricultor;
			}
			set
			{
				if ((this._IdAgricultor != value))
				{
					this.OnIdAgricultorChanging(value);
					this.SendPropertyChanging();
					this._IdAgricultor = value;
					this.SendPropertyChanged("IdAgricultor");
					this.OnIdAgricultorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rut", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Rut
		{
			get
			{
				return this._Rut;
			}
			set
			{
				if ((this._Rut != value))
				{
					this.OnRutChanging(value);
					this.SendPropertyChanging();
					this._Rut = value;
					this.SendPropertyChanged("Rut");
					this.OnRutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Habilitado", DbType="Bit NOT NULL")]
		public bool Habilitado
		{
			get
			{
				return this._Habilitado;
			}
			set
			{
				if ((this._Habilitado != value))
				{
					this.OnHabilitadoChanging(value);
					this.SendPropertyChanging();
					this._Habilitado = value;
					this.SendPropertyChanged("Habilitado");
					this.OnHabilitadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Int NOT NULL")]
		public int IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this.OnIdProveedorChanging(value);
					this.SendPropertyChanging();
					this._IdProveedor = value;
					this.SendPropertyChanged("IdProveedor");
					this.OnIdProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileTag", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MobileTag
		{
			get
			{
				return this._MobileTag;
			}
			set
			{
				if ((this._MobileTag != value))
				{
					this.OnMobileTagChanging(value);
					this.SendPropertyChanging();
					this._MobileTag = value;
					this.SendPropertyChanged("MobileTag");
					this.OnMobileTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIns", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserIns
		{
			get
			{
				return this._UserIns;
			}
			set
			{
				if ((this._UserIns != value))
				{
					this.OnUserInsChanging(value);
					this.SendPropertyChanging();
					this._UserIns = value;
					this.SendPropertyChanged("UserIns");
					this.OnUserInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraIns", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHoraIns
		{
			get
			{
				return this._FechaHoraIns;
			}
			set
			{
				if ((this._FechaHoraIns != value))
				{
					this.OnFechaHoraInsChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraIns = value;
					this.SendPropertyChanged("FechaHoraIns");
					this.OnFechaHoraInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpIns", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IpIns
		{
			get
			{
				return this._IpIns;
			}
			set
			{
				if ((this._IpIns != value))
				{
					this.OnIpInsChanging(value);
					this.SendPropertyChanging();
					this._IpIns = value;
					this.SendPropertyChanged("IpIns");
					this.OnIpInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserUpd", DbType="VarChar(50)")]
		public string UserUpd
		{
			get
			{
				return this._UserUpd;
			}
			set
			{
				if ((this._UserUpd != value))
				{
					this.OnUserUpdChanging(value);
					this.SendPropertyChanging();
					this._UserUpd = value;
					this.SendPropertyChanged("UserUpd");
					this.OnUserUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraUpd", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaHoraUpd
		{
			get
			{
				return this._FechaHoraUpd;
			}
			set
			{
				if ((this._FechaHoraUpd != value))
				{
					this.OnFechaHoraUpdChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraUpd = value;
					this.SendPropertyChanged("FechaHoraUpd");
					this.OnFechaHoraUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpUpd", DbType="VarChar(50)")]
		public string IpUpd
		{
			get
			{
				return this._IpUpd;
			}
			set
			{
				if ((this._IpUpd != value))
				{
					this.OnIpUpdChanging(value);
					this.SendPropertyChanging();
					this._IpUpd = value;
					this.SendPropertyChanged("IpUpd");
					this.OnIpUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fono1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Fono1
		{
			get
			{
				return this._Fono1;
			}
			set
			{
				if ((this._Fono1 != value))
				{
					this.OnFono1Changing(value);
					this.SendPropertyChanging();
					this._Fono1 = value;
					this.SendPropertyChanged("Fono1");
					this.OnFono1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fono2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Fono2
		{
			get
			{
				return this._Fono2;
			}
			set
			{
				if ((this._Fono2 != value))
				{
					this.OnFono2Changing(value);
					this.SendPropertyChanging();
					this._Fono2 = value;
					this.SendPropertyChanged("Fono2");
					this.OnFono2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen", DbType="Int NOT NULL")]
		public int Origen
		{
			get
			{
				return this._Origen;
			}
			set
			{
				if ((this._Origen != value))
				{
					this.OnOrigenChanging(value);
					this.SendPropertyChanging();
					this._Origen = value;
					this.SendPropertyChanged("Origen");
					this.OnOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOleotop", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IDOleotop
		{
			get
			{
				return this._IDOleotop;
			}
			set
			{
				if ((this._IDOleotop != value))
				{
					this.OnIDOleotopChanging(value);
					this.SendPropertyChanging();
					this._IDOleotop = value;
					this.SendPropertyChanged("IDOleotop");
					this.OnIDOleotopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAvenatop", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IDAvenatop
		{
			get
			{
				return this._IDAvenatop;
			}
			set
			{
				if ((this._IDAvenatop != value))
				{
					this.OnIDAvenatopChanging(value);
					this.SendPropertyChanging();
					this._IDAvenatop = value;
					this.SendPropertyChanged("IDAvenatop");
					this.OnIDAvenatopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDGranotop", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IDGranotop
		{
			get
			{
				return this._IDGranotop;
			}
			set
			{
				if ((this._IDGranotop != value))
				{
					this.OnIDGranotopChanging(value);
					this.SendPropertyChanging();
					this._IDGranotop = value;
					this.SendPropertyChanged("IDGranotop");
					this.OnIDGranotopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSAPSync", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastSAPSync
		{
			get
			{
				return this._LastSAPSync;
			}
			set
			{
				if ((this._LastSAPSync != value))
				{
					this.OnLastSAPSyncChanging(value);
					this.SendPropertyChanging();
					this._LastSAPSync = value;
					this.SendPropertyChanged("LastSAPSync");
					this.OnLastSAPSyncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogin", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> LastLogin
		{
			get
			{
				return this._LastLogin;
			}
			set
			{
				if ((this._LastLogin != value))
				{
					this.OnLastLoginChanging(value);
					this.SendPropertyChanging();
					this._LastLogin = value;
					this.SendPropertyChanged("LastLogin");
					this.OnLastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyAccessOleotop", DbType="Bit")]
		public System.Nullable<bool> LegacyAccessOleotop
		{
			get
			{
				return this._LegacyAccessOleotop;
			}
			set
			{
				if ((this._LegacyAccessOleotop != value))
				{
					this.OnLegacyAccessOleotopChanging(value);
					this.SendPropertyChanging();
					this._LegacyAccessOleotop = value;
					this.SendPropertyChanged("LegacyAccessOleotop");
					this.OnLegacyAccessOleotopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyAccessAvenatop", DbType="Bit")]
		public System.Nullable<bool> LegacyAccessAvenatop
		{
			get
			{
				return this._LegacyAccessAvenatop;
			}
			set
			{
				if ((this._LegacyAccessAvenatop != value))
				{
					this.OnLegacyAccessAvenatopChanging(value);
					this.SendPropertyChanging();
					this._LegacyAccessAvenatop = value;
					this.SendPropertyChanged("LegacyAccessAvenatop");
					this.OnLegacyAccessAvenatopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyAccessGranotop", DbType="Bit")]
		public System.Nullable<bool> LegacyAccessGranotop
		{
			get
			{
				return this._LegacyAccessGranotop;
			}
			set
			{
				if ((this._LegacyAccessGranotop != value))
				{
					this.OnLegacyAccessGranotopChanging(value);
					this.SendPropertyChanging();
					this._LegacyAccessGranotop = value;
					this.SendPropertyChanged("LegacyAccessGranotop");
					this.OnLegacyAccessGranotopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MustChangePassword", DbType="Bit")]
		public System.Nullable<bool> MustChangePassword
		{
			get
			{
				return this._MustChangePassword;
			}
			set
			{
				if ((this._MustChangePassword != value))
				{
					this.OnMustChangePasswordChanging(value);
					this.SendPropertyChanging();
					this._MustChangePassword = value;
					this.SendPropertyChanged("MustChangePassword");
					this.OnMustChangePasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSaprosem", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IDSaprosem
		{
			get
			{
				return this._IDSaprosem;
			}
			set
			{
				if ((this._IDSaprosem != value))
				{
					this.OnIDSaprosemChanging(value);
					this.SendPropertyChanging();
					this._IDSaprosem = value;
					this.SendPropertyChanged("IDSaprosem");
					this.OnIDSaprosemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdForceManager", DbType="Int")]
		public System.Nullable<int> IdForceManager
		{
			get
			{
				return this._IdForceManager;
			}
			set
			{
				if ((this._IdForceManager != value))
				{
					this.OnIdForceManagerChanging(value);
					this.SendPropertyChanging();
					this._IdForceManager = value;
					this.SendPropertyChanged("IdForceManager");
					this.OnIdForceManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Agricultor_UsuarioAgricultor", Storage="_UsuarioAgricultor", ThisKey="IdAgricultor", OtherKey="IdAgricultor")]
		public EntitySet<UsuarioAgricultor> UsuarioAgricultor
		{
			get
			{
				return this._UsuarioAgricultor;
			}
			set
			{
				this._UsuarioAgricultor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UsuarioAgricultor(UsuarioAgricultor entity)
		{
			this.SendPropertyChanging();
			entity.Agricultor = this;
		}
		
		private void detach_UsuarioAgricultor(UsuarioAgricultor entity)
		{
			this.SendPropertyChanging();
			entity.Agricultor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYS_User")]
	public partial class SYS_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _UserName;
		
		private string _FullName;
		
		private string _Password;
		
		private bool _Disabled;
		
		private System.Nullable<System.DateTime> _LastLogin;
		
		private string _Email;
		
		private string _UserIns;
		
		private System.DateTime _FechaHoraIns;
		
		private string _IpIns;
		
		private string _UserUpd;
		
		private System.Nullable<System.DateTime> _FechaHoraUpd;
		
		private string _IpUpd;
		
		private System.Nullable<int> _IdSeccion;
		
		private string _Telefono;
		
		private EntitySet<UsuarioAgricultor> _UsuarioAgricultor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnDisabledChanging(bool value);
    partial void OnDisabledChanged();
    partial void OnLastLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUserInsChanging(string value);
    partial void OnUserInsChanged();
    partial void OnFechaHoraInsChanging(System.DateTime value);
    partial void OnFechaHoraInsChanged();
    partial void OnIpInsChanging(string value);
    partial void OnIpInsChanged();
    partial void OnUserUpdChanging(string value);
    partial void OnUserUpdChanged();
    partial void OnFechaHoraUpdChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraUpdChanged();
    partial void OnIpUpdChanging(string value);
    partial void OnIpUpdChanged();
    partial void OnIdSeccionChanging(System.Nullable<int> value);
    partial void OnIdSeccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    #endregion
		
		public SYS_User()
		{
			this._UsuarioAgricultor = new EntitySet<UsuarioAgricultor>(new Action<UsuarioAgricultor>(this.attach_UsuarioAgricultor), new Action<UsuarioAgricultor>(this.detach_UsuarioAgricultor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Bit NOT NULL")]
		public bool Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogin", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> LastLogin
		{
			get
			{
				return this._LastLogin;
			}
			set
			{
				if ((this._LastLogin != value))
				{
					this.OnLastLoginChanging(value);
					this.SendPropertyChanging();
					this._LastLogin = value;
					this.SendPropertyChanged("LastLogin");
					this.OnLastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIns", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserIns
		{
			get
			{
				return this._UserIns;
			}
			set
			{
				if ((this._UserIns != value))
				{
					this.OnUserInsChanging(value);
					this.SendPropertyChanging();
					this._UserIns = value;
					this.SendPropertyChanged("UserIns");
					this.OnUserInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraIns", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHoraIns
		{
			get
			{
				return this._FechaHoraIns;
			}
			set
			{
				if ((this._FechaHoraIns != value))
				{
					this.OnFechaHoraInsChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraIns = value;
					this.SendPropertyChanged("FechaHoraIns");
					this.OnFechaHoraInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpIns", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IpIns
		{
			get
			{
				return this._IpIns;
			}
			set
			{
				if ((this._IpIns != value))
				{
					this.OnIpInsChanging(value);
					this.SendPropertyChanging();
					this._IpIns = value;
					this.SendPropertyChanged("IpIns");
					this.OnIpInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserUpd", DbType="VarChar(50)")]
		public string UserUpd
		{
			get
			{
				return this._UserUpd;
			}
			set
			{
				if ((this._UserUpd != value))
				{
					this.OnUserUpdChanging(value);
					this.SendPropertyChanging();
					this._UserUpd = value;
					this.SendPropertyChanged("UserUpd");
					this.OnUserUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraUpd", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaHoraUpd
		{
			get
			{
				return this._FechaHoraUpd;
			}
			set
			{
				if ((this._FechaHoraUpd != value))
				{
					this.OnFechaHoraUpdChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraUpd = value;
					this.SendPropertyChanged("FechaHoraUpd");
					this.OnFechaHoraUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpUpd", DbType="VarChar(50)")]
		public string IpUpd
		{
			get
			{
				return this._IpUpd;
			}
			set
			{
				if ((this._IpUpd != value))
				{
					this.OnIpUpdChanging(value);
					this.SendPropertyChanging();
					this._IpUpd = value;
					this.SendPropertyChanged("IpUpd");
					this.OnIpUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSeccion", DbType="Int")]
		public System.Nullable<int> IdSeccion
		{
			get
			{
				return this._IdSeccion;
			}
			set
			{
				if ((this._IdSeccion != value))
				{
					this.OnIdSeccionChanging(value);
					this.SendPropertyChanging();
					this._IdSeccion = value;
					this.SendPropertyChanged("IdSeccion");
					this.OnIdSeccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(11)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SYS_User_UsuarioAgricultor", Storage="_UsuarioAgricultor", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<UsuarioAgricultor> UsuarioAgricultor
		{
			get
			{
				return this._UsuarioAgricultor;
			}
			set
			{
				this._UsuarioAgricultor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UsuarioAgricultor(UsuarioAgricultor entity)
		{
			this.SendPropertyChanging();
			entity.SYS_User = this;
		}
		
		private void detach_UsuarioAgricultor(UsuarioAgricultor entity)
		{
			this.SendPropertyChanging();
			entity.SYS_User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsuarioAgricultor")]
	public partial class UsuarioAgricultor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuarioAgricultor;
		
		private int _UserID;
		
		private int _IdAgricultor;
		
		private string _MobileTag;
		
		private string _UserIns;
		
		private System.DateTime _FechaHoraIns;
		
		private string _IpIns;
		
		private string _UserUpd;
		
		private System.Nullable<System.DateTime> _FechaHoraUpd;
		
		private string _IpUpd;
		
		private EntityRef<Agricultor> _Agricultor;
		
		private EntityRef<SYS_User> _SYS_User;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioAgricultorChanging(int value);
    partial void OnIdUsuarioAgricultorChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnIdAgricultorChanging(int value);
    partial void OnIdAgricultorChanged();
    partial void OnMobileTagChanging(string value);
    partial void OnMobileTagChanged();
    partial void OnUserInsChanging(string value);
    partial void OnUserInsChanged();
    partial void OnFechaHoraInsChanging(System.DateTime value);
    partial void OnFechaHoraInsChanged();
    partial void OnIpInsChanging(string value);
    partial void OnIpInsChanged();
    partial void OnUserUpdChanging(string value);
    partial void OnUserUpdChanged();
    partial void OnFechaHoraUpdChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraUpdChanged();
    partial void OnIpUpdChanging(string value);
    partial void OnIpUpdChanged();
    #endregion
		
		public UsuarioAgricultor()
		{
			this._Agricultor = default(EntityRef<Agricultor>);
			this._SYS_User = default(EntityRef<SYS_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioAgricultor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuarioAgricultor
		{
			get
			{
				return this._IdUsuarioAgricultor;
			}
			set
			{
				if ((this._IdUsuarioAgricultor != value))
				{
					this.OnIdUsuarioAgricultorChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioAgricultor = value;
					this.SendPropertyChanged("IdUsuarioAgricultor");
					this.OnIdUsuarioAgricultorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._SYS_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAgricultor", DbType="Int NOT NULL")]
		public int IdAgricultor
		{
			get
			{
				return this._IdAgricultor;
			}
			set
			{
				if ((this._IdAgricultor != value))
				{
					if (this._Agricultor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAgricultorChanging(value);
					this.SendPropertyChanging();
					this._IdAgricultor = value;
					this.SendPropertyChanged("IdAgricultor");
					this.OnIdAgricultorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileTag", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MobileTag
		{
			get
			{
				return this._MobileTag;
			}
			set
			{
				if ((this._MobileTag != value))
				{
					this.OnMobileTagChanging(value);
					this.SendPropertyChanging();
					this._MobileTag = value;
					this.SendPropertyChanged("MobileTag");
					this.OnMobileTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIns", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserIns
		{
			get
			{
				return this._UserIns;
			}
			set
			{
				if ((this._UserIns != value))
				{
					this.OnUserInsChanging(value);
					this.SendPropertyChanging();
					this._UserIns = value;
					this.SendPropertyChanged("UserIns");
					this.OnUserInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraIns", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHoraIns
		{
			get
			{
				return this._FechaHoraIns;
			}
			set
			{
				if ((this._FechaHoraIns != value))
				{
					this.OnFechaHoraInsChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraIns = value;
					this.SendPropertyChanged("FechaHoraIns");
					this.OnFechaHoraInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpIns", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IpIns
		{
			get
			{
				return this._IpIns;
			}
			set
			{
				if ((this._IpIns != value))
				{
					this.OnIpInsChanging(value);
					this.SendPropertyChanging();
					this._IpIns = value;
					this.SendPropertyChanged("IpIns");
					this.OnIpInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserUpd", DbType="VarChar(50)")]
		public string UserUpd
		{
			get
			{
				return this._UserUpd;
			}
			set
			{
				if ((this._UserUpd != value))
				{
					this.OnUserUpdChanging(value);
					this.SendPropertyChanging();
					this._UserUpd = value;
					this.SendPropertyChanged("UserUpd");
					this.OnUserUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraUpd", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaHoraUpd
		{
			get
			{
				return this._FechaHoraUpd;
			}
			set
			{
				if ((this._FechaHoraUpd != value))
				{
					this.OnFechaHoraUpdChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraUpd = value;
					this.SendPropertyChanged("FechaHoraUpd");
					this.OnFechaHoraUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpUpd", DbType="VarChar(50)")]
		public string IpUpd
		{
			get
			{
				return this._IpUpd;
			}
			set
			{
				if ((this._IpUpd != value))
				{
					this.OnIpUpdChanging(value);
					this.SendPropertyChanging();
					this._IpUpd = value;
					this.SendPropertyChanged("IpUpd");
					this.OnIpUpdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Agricultor_UsuarioAgricultor", Storage="_Agricultor", ThisKey="IdAgricultor", OtherKey="IdAgricultor", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Agricultor Agricultor
		{
			get
			{
				return this._Agricultor.Entity;
			}
			set
			{
				Agricultor previousValue = this._Agricultor.Entity;
				if (((previousValue != value) 
							|| (this._Agricultor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Agricultor.Entity = null;
						previousValue.UsuarioAgricultor.Remove(this);
					}
					this._Agricultor.Entity = value;
					if ((value != null))
					{
						value.UsuarioAgricultor.Add(this);
						this._IdAgricultor = value.IdAgricultor;
					}
					else
					{
						this._IdAgricultor = default(int);
					}
					this.SendPropertyChanged("Agricultor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SYS_User_UsuarioAgricultor", Storage="_SYS_User", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public SYS_User SYS_User
		{
			get
			{
				return this._SYS_User.Entity;
			}
			set
			{
				SYS_User previousValue = this._SYS_User.Entity;
				if (((previousValue != value) 
							|| (this._SYS_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SYS_User.Entity = null;
						previousValue.UsuarioAgricultor.Remove(this);
					}
					this._SYS_User.Entity = value;
					if ((value != null))
					{
						value.UsuarioAgricultor.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("SYS_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
