//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrotop.PROCEA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JFERNANDEZ;Initial Catalog=agrofichas;Persist Security Info=True;User" +
            " ID=SA;Password=saprosem")]
        public string agrofichasConnectionString {
            get {
                return ((string)(this["agrofichasConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Microsoft OneDrive\\Proyectos\\Empresas Agrotop\\Desarrollos\\Agrotop.AgroFichas.A" +
            "PI\\Agrotop.PROCEA\\App_Data\\EmailTemplates")]
        public string EmailTemplatesFolder {
            get {
                return ((string)(this["EmailTemplatesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Microsoft OneDrive\\Proyectos\\Empresas Agrotop\\Desarrollos\\Agrotop.AgroFichas.A" +
            "PI\\Agrotop.PROCEA\\App_Data\\XmlFiles")]
        public string XmlFilesFolder {
            get {
                return ((string)(this["XmlFilesFolder"]));
            }
        }
    }
}
